/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package riskid.risk.game.kayttoliittyma;

/**
 *
 * @author imatias
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tekstiKentta = new javax.swing.JTextField();
        nappi = new javax.swing.JButton();
        ilmoitukset = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        tekstiKentta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstiKenttaActionPerformed(evt);
            }
        });
        getContentPane().add(tekstiKentta);
        tekstiKentta.setBounds(50, 600, 120, 30);

        nappi.setText("ok");
        nappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nappiActionPerformed(evt);
            }
        });
        getContentPane().add(nappi);
        nappi.setBounds(180, 600, 110, 30);

        ilmoitukset.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        ilmoitukset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 1, true));
        getContentPane().add(ilmoitukset);
        ilmoitukset.setBounds(320, 600, 740, 30);

        jLabel1.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TlwgTypewriter", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 90, 30);

        jLabel2.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TlwgTypewriter", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 60, 90, 30);

        jLabel3.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TlwgTypewriter", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 30, 90, 30);

        jLabel4.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TlwgTypewriter", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 120, 90, 30);

        jLabel5.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TlwgTypewriter", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 100, 90, 30);

        jLabel6.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "6", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TlwgTypewriter", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 130, 90, 30);

        jLabel7.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "7", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TlwgTypewriter", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 160, 90, 30);

        jLabel8.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "8", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TlwgTypewriter", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 190, 90, 30);

        jLabel9.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "9", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TlwgTypewriter", 0, 12), new java.awt.Color(254, 254, 254))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 250, 90, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalRisk.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1100, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tekstiKenttaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstiKenttaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tekstiKenttaActionPerformed

    private void nappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nappiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nappiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel ilmoitukset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton nappi;
    private javax.swing.JTextField tekstiKentta;
    // End of variables declaration//GEN-END:variables
}
